blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/prn-tf/alexander-storage#readme
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/prn-tf/alexander-storage/discussions
    about: Ask questions and discuss ideas in Discussions
